version: '3.7'

services:

  backuppc:
    image: adferrand/backuppc
    container_name: backuppc
    hostname: backuppc
    ports:
      - 443:8080
    environment:
      - TZ=Europe/Paris
      - USE_SSL=true
    volumes:
      - /DockerData/Backuppc/etc:/etc/backuppc
      - /DockerData/Backuppc/home:/home/backuppc
      - /DockerData/Backuppc/data:/data/backuppc
    restart: always
