# Image de base
FROM debian:stretch

# Installation de apache2
RUN apt-get update && apt-get install -y apache2 curl unzip && apt-get clean &&$

#Mise en place des environnements
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
