version: '3.7'

services:
  mybb:
    container_name: mybb-phpfpm
    image: mybb/mybb:latest
    volumes:
      - /DockerData/Mybb/mybb:/var/www/html:rw
    networks:
      - traefik
    restart: always

  nginx:
    container_name: mybb-nginx
    image: nginx:mainline
    #ports:
    #  - published: 8080
    #  target: 80
    volumes:
      - /DockerData/Mybb/mybb:/var/www/html:ro
      - /DockerData/Mybb/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.frontend.rule=Host:mybb.voxintra"
    links:
      - mybb
    networks:
      - traefik
    restart: always

  postgresql:
    container_name: mybb-postrgesql
    #hostname: kanboard-mariadb
    environment:
      POSTGRES_DB: mybb
      POSTGRES_PASSWORD: XXXXXXXXXXX
      POSTGRES_USER: mybb
    image: postgres:11.3
    volumes:
      - /DockerData/Mybb/postgres/data:/var/lib/postgresql/data:rw
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external:
      name: traefik_default
