version: '3.7'

services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      # Data persistency
      # sudo mkdir -p /DockerData/Influxdb/data
      - /DockerData/Influxdb/data:/var/lib/influxdb
    restart: always
